### ISSUE TITLE
AttendanceDao_Impl.java line 87

### ISSUE THREAD

**Issue by aiyu-ayaan** [aiyu-ayaan/BIT-App#35]
```
Fatal Exception: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=6
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:155)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:142)
       at com.atech.core.data.room.attendance.AttendanceDao_Impl$12.call(AttendanceDao_Impl.java:87)
       at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.java:84)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by alperozoner** [comment]
Are you talking about this line: 
at com.atech.core.data.room.attendance.AttendanceDao_Impl$12.call(AttendanceDao_Impl.java:87)
I am not pretty sure what the bug is.

**Comment by aiyu-ayaan** [comment]
No, I am talking about  **Row too big to fit into CursorWindow requiredPos=0, totalRows=6**  
line. Maybe BUG is in 1 line only. I just copied from Crashlytics
